services:
  jangcar:
    container_name: jangcar
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5434:5432

  jangcar_redis:
    container_name: jangcar_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - 6382:6379